Description: EC2 script

Parameters:
  InstanceId:
    Description: Instance Id from AWS repo
    Type: String
    Default: ami-0d593311db5abb72b
  InstanceType:
    Description: Instance type
    Type: String
    Default: t2.micro
    AllowedValues:
    - t2.micro
    - t2.small
    - t2.medium
  SshKeyName:
    Description: Instance access key
    Type: AWS::EC2::KeyPair::KeyName
    Default: andriy.aws
  MyUserData:
    Type: String  

Resources:

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable HTTP access via port 80 + SSH access"
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22 

  LaunchTemplateWeek1:
    Type: AWS::EC2::LaunchTemplate
    DependsOn: WebServerSecurityGroup
    Properties:
      LaunchTemplateName: !Sub ${AWS::StackName}-launch-template
      LaunchTemplateData:
        ImageId:
          Ref: InstanceId     
        InstanceType: 
          Ref: InstanceType
        SecurityGroupIds:
        - !GetAtt WebServerSecurityGroup.GroupId
        UserData: !Ref MyUserData
          # Fn::Base64:
          #   !Sub |
          #     #!/bin/bash
          #     sudo apt-get update
          #     sudo apt-get install openjdk-8-jdk
        TagSpecifications:
        - ResourceType: instance
          Tags:
          - Key: environment
            Value: development
        - ResourceType: volume
          Tags:
          - Key: environment
            Value: development   
        KeyName:
          Ref: SshKeyName     

  ASGWeek1:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: ASG1
      VPCZoneIdentifier:
      - subnet-06d3c714157088e17
      - subnet-03cef44ce2c838b8e
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplateWeek1
        Version: !GetAtt LaunchTemplateWeek1.LatestVersionNumber
      MaxSize: '3'
      MinSize: '1'
      DesiredCapacity: '2'  

Outputs:
  ASGdetials:
    Description: ASG details
    Value: !Ref ASGWeek1
