Description: EC2 script

Parameters:
  InstanceId:
    Description: Instance Id from AWS repo
    Type: String
    Default: ami-0d593311db5abb72b
  InstanceType:
    Description: Instance type
    Type: String
    Default: t2.micro
    AllowedValues:
    - t2.micro
    - t2.small
    - t2.medium
  SshKeyName:
    Description: Instance access key
    Type: AWS::EC2::KeyPair::KeyName
    Default: andriy.aws

Resources:
  MyEc2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 
        Ref: InstanceId     
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: SshKeyName
      SecurityGroups:
      - Ref: WebServerSecurityGroup

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable HTTP access via port 80 + SSH access"
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22 

Outputs:
  MyEc2Ip:
    Description: The Instance IP
    Value: !GetAtt MyEc2.PublicIp